
import Mysql.MySqlDatabase;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class CLIENT_WINDOWS extends javax.swing.JFrame {

    /**
     * Creates new form CLIENT_WINDOWS
     */
    public CLIENT_WINDOWS() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_firstname = new javax.swing.JLabel();
        jTextField_firstname1 = new javax.swing.JLabel();
        jTextField_firstname3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_AddOwner2 = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jPanel_Title = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_firstname2 = new javax.swing.JLabel();
        jTextField_Name1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_LAstnasme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_LAstnasme1 = new javax.swing.JTextField();
        jTextField_LAstnasme2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_LAstnasme3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_AddOwner1 = new javax.swing.JButton();
        jButton_AddOwner3 = new javax.swing.JButton();
        jButton_AddOwner4 = new javax.swing.JButton();
        jButton_AddOwner5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTextField_firstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_firstname.setText("First Name:");

        jTextField_firstname1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_firstname1.setText("First Name:");

        jTextField_firstname3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_firstname3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Phone:");

        jButton_AddOwner2.setBackground(new java.awt.Color(0, 204, 51));
        jButton_AddOwner2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddOwner2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddOwner2.setText("ADD");
        jButton_AddOwner2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddOwner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOwner2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_idKeyPressed(evt);
            }
        });

        jPanel_Title.setBackground(new java.awt.Color(0, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setText("            CLIENTS");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ID:");

        jTextField_firstname2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_firstname2.setText("First Name:");

        jTextField_Name1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Name1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Last Name:");

        jTextField_LAstnasme.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Phone:");

        jTextField_LAstnasme1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField_LAstnasme2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Email:");

        jTextField_LAstnasme3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Address:");

        jButton_AddOwner1.setBackground(new java.awt.Color(0, 204, 51));
        jButton_AddOwner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddOwner1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddOwner1.setText("Add");
        jButton_AddOwner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddOwner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOwner1ActionPerformed(evt);
            }
        });

        jButton_AddOwner3.setBackground(new java.awt.Color(255, 153, 102));
        jButton_AddOwner3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddOwner3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddOwner3.setText("Remove");
        jButton_AddOwner3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddOwner3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOwner3ActionPerformed(evt);
            }
        });

        jButton_AddOwner4.setBackground(new java.awt.Color(0, 204, 255));
        jButton_AddOwner4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddOwner4.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddOwner4.setText("Edit");
        jButton_AddOwner4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddOwner4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOwner4ActionPerformed(evt);
            }
        });

        jButton_AddOwner5.setBackground(new java.awt.Color(255, 153, 102));
        jButton_AddOwner5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddOwner5.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddOwner5.setText("Refresh");
        jButton_AddOwner5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddOwner5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOwner5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "suresh", "8982222224", "suresh@gmail", "srpf"},
                {"2", "ramesh", "7899556365", "ramesh@gmail", "srpf"},
                {"3", "rajesh", "7985626556", "rajesh@gmail", "rggdf"},
                {"4", "mukesh", "8741296025", "mukesh", null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_firstname2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_LAstnasme, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LAstnasme1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_AddOwner1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton_AddOwner4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButton_AddOwner3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jButton_AddOwner5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_LAstnasme3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_LAstnasme2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addGap(34, 34, 34))
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_firstname2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LAstnasme1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LAstnasme, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LAstnasme2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LAstnasme3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddOwner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AddOwner4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AddOwner3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AddOwner5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idKeyPressed

    private void jTextField_Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Name1ActionPerformed

    private void jButton_AddOwner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOwner1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
        //add a new Type
        
        MyDB db=new MyDB();
      //int x=  db.Insert(jTextField_id.getText(),jTextField_Name.getText(), jTextArea_Description.getText());
        //jTextField_id.setText(x+"");
          String d="<html><body><div>";
      MySqlDatabase ms=new MySqlDatabase("PropTan","property_type", "root", "root"); 
        for (int i = 1; i <=Integer.parseInt(jTextField_id.getText()); i++) {
          String [] data= ms.GetValues("idPropTan", i+"", 3);
          d+="<p>"+data[0]+"&nbsp;&nbsp;&nbsp;"+data[1]+"&nbsp;&nbsp;&nbsp;"+data[2]+"</p>";      
        }
      d+="</div></body></html>";
      jLabel4.setText(d);
      

    }//GEN-LAST:event_jButton_AddOwner1ActionPerformed

    private void jButton_AddOwner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOwner2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddOwner2ActionPerformed

    private void jButton_AddOwner3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOwner3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddOwner3ActionPerformed

    private void jButton_AddOwner4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOwner4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddOwner4ActionPerformed

    private void jButton_AddOwner5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOwner5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddOwner5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENT_WINDOWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENT_WINDOWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENT_WINDOWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENT_WINDOWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENT_WINDOWS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddOwner1;
    private javax.swing.JButton jButton_AddOwner2;
    private javax.swing.JButton jButton_AddOwner3;
    private javax.swing.JButton jButton_AddOwner4;
    private javax.swing.JButton jButton_AddOwner5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_LAstnasme;
    private javax.swing.JTextField jTextField_LAstnasme1;
    private javax.swing.JTextField jTextField_LAstnasme2;
    private javax.swing.JTextField jTextField_LAstnasme3;
    private javax.swing.JTextField jTextField_Name1;
    private javax.swing.JLabel jTextField_firstname;
    private javax.swing.JLabel jTextField_firstname1;
    private javax.swing.JLabel jTextField_firstname2;
    private javax.swing.JLabel jTextField_firstname3;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
}
