
import java.awt.Color;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.border.MatteBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class MAIN_APP_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_APP_WINDOW
     */
    public MAIN_APP_WINDOW() {
        initComponents();
        //set the logo picture
        jLabel_APP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")));
          jLabel_pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ppp.jpg")));
        //set the logo bordeers
        MatteBorder logo_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_APP.setBorder(logo_border);
        
        //set border of the name label
         MatteBorder appname_border=BorderFactory.createMatteBorder(0, 0, 3, 0, Color.white);
        jLabel1.setBorder(appname_border);
        
        
        //set border of the menu item
         MatteBorder menu_items_border=BorderFactory.createMatteBorder(0, 0, 1, 0, Color.YELLOW);
        jLabel_Property.setBorder(menu_items_border);
        jLabel_Proprtytype.setBorder(menu_items_border);
        jLabel_Propertyimage.setBorder(menu_items_border);
        jLabel_Propertyowner.setBorder(menu_items_border);
        jLabel_client.setBorder(menu_items_border);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_APP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Proprtytype = new javax.swing.JLabel();
        jLabel_Propertyimage = new javax.swing.JLabel();
        jLabel_Propertyowner = new javax.swing.JLabel();
        jLabel_Property = new javax.swing.JLabel();
        jLabel_client = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_pp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        jLabel_APP.setBackground(new java.awt.Color(51, 204, 255));
        jLabel_APP.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My APP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_APP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_APP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel_Proprtytype.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Proprtytype.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Proprtytype.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Proprtytype.setText("   Property-Type");
        jLabel_Proprtytype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Proprtytype.setOpaque(true);
        jLabel_Proprtytype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ProprtytypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ProprtytypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ProprtytypeMouseExited(evt);
            }
        });

        jLabel_Propertyimage.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Propertyimage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Propertyimage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Propertyimage.setText("   Property-Image");
        jLabel_Propertyimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Propertyimage.setOpaque(true);
        jLabel_Propertyimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PropertyimageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PropertyimageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PropertyimageMouseExited(evt);
            }
        });

        jLabel_Propertyowner.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Propertyowner.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Propertyowner.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Propertyowner.setText("   Property-Owner");
        jLabel_Propertyowner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Propertyowner.setOpaque(true);
        jLabel_Propertyowner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PropertyownerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PropertyownerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PropertyownerMouseExited(evt);
            }
        });

        jLabel_Property.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Property.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Property.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Property.setText("   Property");
        jLabel_Property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Property.setOpaque(true);
        jLabel_Property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PropertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PropertyMouseExited(evt);
            }
        });

        jLabel_client.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_client.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_client.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_client.setText("   Client");
        jLabel_client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_client.setOpaque(true);
        jLabel_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Propertyimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Proprtytype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Propertyowner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_Property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel_Proprtytype, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Propertyimage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Propertyowner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_client, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel_Property, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setOpaque(true);

        jLabel3.setText("@ copywrite  RGCER STUDENT 2022   3 _YEAR    ");

        jLabel_pp.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_pp.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_pp, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_pp, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_PropertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyMouseEntered
        // TODO add your handling code here:
        
        jLabel_Property.setBackground(Color.white);
        jLabel_Property.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_jLabel_PropertyMouseEntered

    private void jLabel_PropertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyMouseExited
        // TODO add your handling code here:
        jLabel_Property.setBackground(new Color(102,102,102));
        jLabel_Property.setForeground(Color.white);    
    }//GEN-LAST:event_jLabel_PropertyMouseExited

    private void jLabel_ProprtytypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProprtytypeMouseEntered
        // TODO add your handling code here:
        jLabel_Proprtytype.setBackground(Color.white);
        jLabel_Proprtytype.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_ProprtytypeMouseEntered

    private void jLabel_ProprtytypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProprtytypeMouseExited
        // TODO add your handling code here:
          jLabel_Proprtytype.setBackground(new Color(102,102,102));
          jLabel_Proprtytype.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_ProprtytypeMouseExited

    private void jLabel_PropertyimageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyimageMouseEntered
        // TODO add your handling code here:
        
         jLabel_Propertyimage.setBackground(Color.white);
        jLabel_Propertyimage.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_PropertyimageMouseEntered

    private void jLabel_PropertyimageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyimageMouseExited
        // TODO add your handling code here:
        
           jLabel_Propertyimage.setBackground(new Color(102,102,102));
          jLabel_Propertyimage.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_PropertyimageMouseExited

    private void jLabel_PropertyownerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyownerMouseEntered
        // TODO add your handling code here:
           jLabel_Propertyowner.setBackground(Color.white);
        jLabel_Propertyowner.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_jLabel_PropertyownerMouseEntered

    private void jLabel_PropertyownerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyownerMouseExited
        // TODO add your handling code here:
         jLabel_Propertyowner.setBackground(new Color(102,102,102));
          jLabel_Propertyowner.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel_PropertyownerMouseExited

    private void jLabel_clientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseEntered
        // TODO add your handling code here:
           jLabel_client.setBackground(Color.white);
        jLabel_client.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_jLabel_clientMouseEntered

    private void jLabel_clientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseExited
        // TODO add your handling code here:
        
         jLabel_client.setBackground(new Color(102,102,102));
          jLabel_client.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_clientMouseExited

    private void jLabel_ProprtytypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProprtytypeMouseClicked
        // TODO add your handling code here:
        
        //open the proprty types  form
       PROPERTY_TYPE_WINDOWS typeform=new PROPERTY_TYPE_WINDOWS();
                        typeform.setVisible(true);
                        typeform.pack();
                        typeform.setLocationRelativeTo(null);
                        typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_ProprtytypeMouseClicked

    private void jLabel_PropertyimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyimageMouseClicked
        // TODO add your handling code here:
         Property_image imageform=new  Property_image();
                        imageform.setVisible(true);
                        imageform.pack();
                        imageform.setLocationRelativeTo(null);
                        imageform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_PropertyimageMouseClicked

    private void jLabel_PropertyownerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyownerMouseClicked
        // TODO add your handling code here:
        
        
        OWNER_WINDOW oform=new OWNER_WINDOW ();
                       oform.setVisible(true);
                        oform.pack();
                        oform.setLocationRelativeTo(null);
                        oform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_PropertyownerMouseClicked

    private void jLabel_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseClicked
        // TODO add your handling code here:
        
        CLIENT_WINDOWS clientform=new CLIENT_WINDOWS();
                         clientform.setVisible(true);
                         clientform.pack();
                           clientform.setLocationRelativeTo(null);
                        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_clientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MAIN_APP_WINDOW().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_APP;
    private javax.swing.JLabel jLabel_Property;
    private javax.swing.JLabel jLabel_Propertyimage;
    private javax.swing.JLabel jLabel_Propertyowner;
    private javax.swing.JLabel jLabel_Proprtytype;
    private javax.swing.JLabel jLabel_client;
    private javax.swing.JLabel jLabel_pp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
